services:
  # A Selenium server running Chrome for running UI tests locally
  selenium-chrome:
    container_name: selenium-chrome
    hostname: selenium
    image: seleniarm/standalone-chromium:latest
    ports:
      - "5900:5900" # The selenium direct VNC port
      - "4444:4444" # The selenium router port
      - "7900:7900" # The selenium NoVNC service port
    expose:
      - "5900" 
      - "4444"
      - "7900"
    environment:
      JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps= -Dwebdriver.chrome.allowedIps=
    shm_size: '2gb'
    # Many default ulimits are just too high
    # And, so, it will consume way too much memory (16GB+)
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    network_mode: host

  # A Selenium server running Firefox for running UI tests locally
  selenium-firefox:
    container_name: selenium-firefox
    hostname: selenium
    image: seleniarm/standalone-firefox:latest
    ports:
      - "5900:5900" # The selenium direct VNC port
      - "4444:4444" # The selenium router port
      - "7900:7900" # The selenium NoVNC service port
    expose:
      - "5900"
      - "4444"
      - "7900"
    shm_size: '2gb'
    # Many default ulimits are just too high
    # And, so, it will consume way too much memory (16GB+)
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    network_mode: host

  # A Selenium server running Edge for running UI tests locally
  selenium-edge:
    container_name: selenium-edge
    hostname: selenium
    image: selenium/standalone-edge:latest
    ports:
      - "5900:5900" # The selenium direct VNC port
      - "4444:4444" # The selenium router port
      - "7900:7900" # The selenium NoVNC service port
    expose:
      - "5900"
      - "4444"
      - "7900"
    shm_size: '2gb'
    # Many default ulimits are just too high
    # And, so, it will consume way too much memory (16GB+)
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    network_mode: host

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    network_mode: host

  db:
    container_name: db
    hostname: db
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql
    # Many default ulimits are just too high
    # And, so, it will consume way too much memory (16GB+)
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
